// generated by astromech db:generate — do not edit; ordering by journal idx
import type { MigrationProvider } from 'kysely';
import * as m0000 from './0000_baseline';
import * as m0001 from './0001_entry_content';

export const migrationProvider: MigrationProvider = {
    async getMigrations() {
        return {
            '0000_baseline': m0000,
            '0001_entry_content': m0001,
        };
    },
};
