// generated by astromech db:generate — do not edit; ordering by journal idx
import type { MigrationProvider } from 'kysely';
import * as m0000 from './0000_baseline';
import * as m0001 from './0001_entry_content';
import * as m0002 from './0002_globals';
import * as m0003 from './0003_media-content';
import * as m0004 from './0004_users-role';
import * as m0005 from './0005_user-content';

export const migrationProvider: MigrationProvider = {
    async getMigrations() {
        return {
            '0000_baseline': m0000,
            '0001_entry_content': m0001,
            '0002_globals': m0002,
            '0003_media-content': m0003,
            '0004_users-role': m0004,
            '0005_user-content': m0005,
        };
    },
};
