// generated by astromech db:generate — do not edit; ordering by journal idx
import type { MigrationProvider } from 'kysely';
import * as m0000 from './0000_baseline.js';
import * as m0001 from './0001_plugins-tracking.js';
import * as m0002 from './0002_plugins-tracking-package.js';
import * as m0003 from './0003_relationships-index.js';
import * as m0004 from './0004_media-title-caption.js';

export const migrationProvider: MigrationProvider = {
    async getMigrations() {
        return {
            '0000_baseline': m0000,
            '0001_plugins-tracking': m0001,
            '0002_plugins-tracking-package': m0002,
            '0003_relationships-index': m0003,
            '0004_media-title-caption': m0004,
        };
    },
};
