import type { Kysely } from 'kysely';
import { sql } from 'kysely';

/**
 * Makes `user_id` on both tables a cascading reference to `users`. Generated by
 * `plugin:generate`, then hand-edited to add the two deletes at the top.
 */
export async function up(db: Kysely<unknown>): Promise<void> {
    // Rows whose user is already gone would fail the new foreign key during the copy.
    await sql`DELETE FROM \`plugin_assistant_approvals\` WHERE \`user_id\` NOT IN (SELECT \`id\` FROM \`users\`)`.execute(
        db
    );
    await sql`DELETE FROM \`plugin_assistant_sessions\` WHERE \`user_id\` NOT IN (SELECT \`id\` FROM \`users\`)`.execute(
        db
    );
    await sql`PRAGMA defer_foreign_keys = true`.execute(db);
    await sql`
        CREATE TABLE \`__new_plugin_assistant_approvals\` (
            \`id\` text PRIMARY KEY NOT NULL,
            \`user_id\` text NOT NULL,
            \`tool_call_id\` text NOT NULL,
            \`method\` text NOT NULL,
            \`tool_name\` text NOT NULL,
            \`arguments\` text,
            \`destructive\` integer NOT NULL,
            \`status\` text NOT NULL CHECK (\`status\` IN ('pending', 'approved', 'rejected', 'expired')),
            \`created_at\` text NOT NULL,
            \`expires_at\` text NOT NULL,
            \`resolved_at\` text,
            CONSTRAINT \`plugin_assistant_approvals_user_id_fkey\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE cascade
        )
    `.execute(db);
    await sql`INSERT INTO \`__new_plugin_assistant_approvals\` (\`id\`, \`user_id\`, \`tool_call_id\`, \`method\`, \`tool_name\`, \`arguments\`, \`destructive\`, \`status\`, \`created_at\`, \`expires_at\`, \`resolved_at\`) SELECT \`id\`, \`user_id\`, \`tool_call_id\`, \`method\`, \`tool_name\`, \`arguments\`, \`destructive\`, \`status\`, \`created_at\`, \`expires_at\`, \`resolved_at\` FROM \`plugin_assistant_approvals\``.execute(
        db
    );
    await sql`DROP TABLE \`plugin_assistant_approvals\``.execute(db);
    await sql`ALTER TABLE \`__new_plugin_assistant_approvals\` RENAME TO \`plugin_assistant_approvals\``.execute(
        db
    );
    await sql`PRAGMA defer_foreign_keys = true`.execute(db);
    await sql`
        CREATE TABLE \`__new_plugin_assistant_sessions\` (
            \`id\` text PRIMARY KEY NOT NULL,
            \`user_id\` text NOT NULL,
            \`messages\` text NOT NULL,
            \`created_at\` text NOT NULL,
            \`updated_at\` text NOT NULL,
            CONSTRAINT \`plugin_assistant_sessions_user_id_fkey\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON UPDATE no action ON DELETE cascade
        )
    `.execute(db);
    await sql`INSERT INTO \`__new_plugin_assistant_sessions\` (\`id\`, \`user_id\`, \`messages\`, \`created_at\`, \`updated_at\`) SELECT \`id\`, \`user_id\`, \`messages\`, \`created_at\`, \`updated_at\` FROM \`plugin_assistant_sessions\``.execute(
        db
    );
    await sql`DROP TABLE \`plugin_assistant_sessions\``.execute(db);
    await sql`ALTER TABLE \`__new_plugin_assistant_sessions\` RENAME TO \`plugin_assistant_sessions\``.execute(
        db
    );
    await sql`CREATE UNIQUE INDEX \`plugin_assistant_sessions_user_id_unique\` ON \`plugin_assistant_sessions\` (\`user_id\`)`.execute(
        db
    );
}
