/**
 * Migration generator — reads/writes an app's `migrations/` directory
 * (`snapshot.json`, `journal.json`, the generated `.ts` migration files, and
 * `index.ts`), wiring `snapshot.ts` (descriptor → snapshot) → `diff.ts`
 * (snapshot diff) → `migration-render.ts` (diff → SQL/TS) into one call.
 *
 * Node-only (uses `node:fs/promises` + `node:path`) — generation is a
 * dev/CI-time step, never a runtime one (`specs/data-layer.md` §7: "Generation
 * = dev/CI only. Application = Kysely Migrator, pure SQL, edge/D1-safe").
 * Do NOT re-export this module from a barrel a browser bundle or a Worker
 * runtime path might pull in (`database/index.ts` / `exports/schema.ts` stay
 * fs-free) — the CLI (`transport/cli/commands/db-generate.ts`) is the only
 * caller.
 *
 * No `id`/`prevId` snapshot-chain (unlike drizzle-kit) — journal ordering is
 * by `idx` alone, and a divergent parallel `db:generate` surfaces as a
 * `snapshot.json` merge conflict rather than a silent hash mismatch.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { diffSnapshots } from '@/database/diff.js';
import { renderMigrationFile } from '@/database/migration-render.js';
import { createSnapshot, serializeSnapshot, type Snapshot } from '@/database/snapshot.js';
import type { SqlDialect } from '@/database/ddl.js';
import type { TableDescriptor } from '@/database/define-table.js';

export type GenerateResult =
    | { status: 'no-changes' }
    | { status: 'generated'; file: string; tag: string; warnings: string[] };

type JournalEntry = { idx: number; tag: string; when: number };
type Journal = { version: 1; dialect: SqlDialect; entries: JournalEntry[] };

/** kebab-case a migration name (`"Add Foo"` / `"addFoo"` → `"add-foo"`). */
function kebabCase(name: string): string {
    return name
        .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
        .trim()
        .replace(/[^a-zA-Z0-9]+/g, '-')
        .toLowerCase()
        .replace(/^-+|-+$/g, '');
}

async function readJsonIfExists<T>(path: string): Promise<T | null> {
    try {
        return JSON.parse(await readFile(path, 'utf-8')) as T;
    } catch (err) {
        if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
        throw err;
    }
}

function migrationVarName(idx: number): string {
    return `m${String(idx).padStart(4, '0')}`;
}

/** Regenerate `index.ts` — the static `MigrationProvider` — from every
 *  journal entry, ordered by `idx`. Static imports only (no dynamic
 *  discovery): the Workers bundler can't do runtime `fs` scanning. */
function renderIndexFile(entries: JournalEntry[]): string {
    const sorted = [...entries].sort((a, b) => a.idx - b.idx);
    const imports = sorted
        .map((e) => `import * as ${migrationVarName(e.idx)} from './${e.tag}.js';`)
        .join('\n');
    const providerEntries = sorted
        .map((e) => `            '${e.tag}': ${migrationVarName(e.idx)},`)
        .join('\n');
    return [
        '// generated by astromech db:generate — do not edit; ordering by journal idx',
        "import type { MigrationProvider } from 'kysely';",
        imports,
        '',
        'export const migrationProvider: MigrationProvider = {',
        '    async getMigrations() {',
        '        return {',
        providerEntries,
        '        };',
        '    },',
        '};',
        '',
    ].join('\n');
}

/**
 * Diff the given descriptors against `<dir>/snapshot.json` and, if anything
 * changed, write a new `NNNN_<name>.ts` migration + regenerate `index.ts` +
 * update `journal.json`/`snapshot.json`. Throws (writing nothing) if the diff
 * has any validation errors. Prints warnings loudly via `console.warn` before
 * writing.
 */
export async function generateMigrations(opts: {
    dir: string;
    tables: TableDescriptor[];
    dialect: SqlDialect;
    name: string;
}): Promise<GenerateResult> {
    const snapshotPath = resolve(opts.dir, 'snapshot.json');
    const journalPath = resolve(opts.dir, 'journal.json');
    const indexPath = resolve(opts.dir, 'index.ts');

    const prev = await readJsonIfExists<Snapshot>(snapshotPath);
    const journal: Journal = (await readJsonIfExists<Journal>(journalPath)) ?? {
        version: 1,
        dialect: opts.dialect,
        entries: [],
    };

    const next = createSnapshot(opts.tables, { dialect: opts.dialect });
    const diff = diffSnapshots(prev, next);

    if (diff.errors.length > 0) {
        throw new Error(
            `[Astromech] migration generation failed:\n` +
                diff.errors.map((e) => `  - ${e}`).join('\n')
        );
    }

    if (diff.ops.length === 0) {
        return { status: 'no-changes' };
    }

    for (const warning of diff.warnings) {
        console.warn(`[astromech db:generate] WARNING: ${warning}`);
    }

    const idx =
        journal.entries.length > 0
            ? Math.max(...journal.entries.map((e) => e.idx)) + 1
            : 0;
    const tag = `${String(idx).padStart(4, '0')}_${kebabCase(opts.name)}`;

    await mkdir(opts.dir, { recursive: true });
    await writeFile(
        resolve(opts.dir, `${tag}.ts`),
        renderMigrationFile(diff.ops, opts.dialect),
        'utf-8'
    );

    journal.entries.push({ idx, tag, when: Date.now() });
    await writeFile(journalPath, `${JSON.stringify(journal, null, 2)}\n`, 'utf-8');
    await writeFile(snapshotPath, `${serializeSnapshot(next)}\n`, 'utf-8');
    await writeFile(indexPath, renderIndexFile(journal.entries), 'utf-8');

    return { status: 'generated', file: `${tag}.ts`, tag, warnings: diff.warnings };
}
