// generated by astromech db:generate — do not edit; ordering by journal idx
import type { MigrationProvider } from 'kysely/migration';
import * as m0000 from './0000_migration';

export const migrationProvider: MigrationProvider = {
    async getMigrations() {
        return {
            '0000_migration': m0000,
        };
    },
};
