/**
 * Migration generator — reads/writes an app's `migrations/` directory
 * (`snapshot.json`, `journal.json`, the generated `.ts` migration files, and
 * `index.ts`), wiring `diff.ts` (snapshot diff) → `render.ts` (diff → SQL/TS)
 * into one call.
 *
 * Node-only (uses `node:fs/promises` + `node:path`) — generation is a dev/CI
 * step, never a runtime one. It is deliberately NOT part of the package's main
 * entry: `.` stays pure and edge-safe, this module is the `./generate` subpath.
 *
 * Journal ordering is by `idx` alone and there is no `id`/`prevId` snapshot
 * chain, so a divergent parallel generation run surfaces as a `snapshot.json`
 * merge conflict rather than a silent hash mismatch.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { diffSnapshots } from './diff.js';
import { renderMigrationFile } from './render.js';
import { serializeSnapshot, type Snapshot, type SqlDialect } from './model.js';

export type GenerateResult =
    | { status: 'no-changes' }
    | { status: 'generated'; file: string; tag: string; warnings: string[] };

type JournalEntry = { idx: number; tag: string; when: number };
type Journal = { version: 1; dialect: SqlDialect; entries: JournalEntry[] };

/** kebab-case a migration name (`"Add Foo"` / `"addFoo"` → `"add-foo"`). */
function kebabCase(name: string): string {
    return name
        .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
        .trim()
        .replace(/[^a-zA-Z0-9]+/g, '-')
        .toLowerCase()
        .replace(/^-+|-+$/g, '');
}

async function readJsonIfExists<T>(path: string): Promise<T | null> {
    try {
        return JSON.parse(await readFile(path, 'utf-8')) as T;
    } catch (err) {
        if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
        throw err;
    }
}

function migrationVarName(idx: number): string {
    return `m${String(idx).padStart(4, '0')}`;
}

/** Regenerate `index.ts` — the static `MigrationProvider` — from every
 *  journal entry, ordered by `idx`. Static imports only (no dynamic
 *  discovery): an edge bundler can't do runtime `fs` scanning. */
function renderIndexFile(entries: JournalEntry[]): string {
    const sorted = [...entries].sort((a, b) => a.idx - b.idx);
    const imports = sorted
        .map((e) => `import * as ${migrationVarName(e.idx)} from './${e.tag}.js';`)
        .join('\n');
    const providerEntries = sorted
        .map((e) => `            '${e.tag}': ${migrationVarName(e.idx)},`)
        .join('\n');
    return [
        '// generated by astromech db:generate — do not edit; ordering by journal idx',
        "import type { MigrationProvider } from 'kysely';",
        imports,
        '',
        'export const migrationProvider: MigrationProvider = {',
        '    async getMigrations() {',
        '        return {',
        providerEntries,
        '        };',
        '    },',
        '};',
        '',
    ].join('\n');
}

/**
 * Diff the given snapshot against `<dir>/snapshot.json` and, if anything
 * changed, write a new `NNNN_<name>.ts` migration + regenerate `index.ts` +
 * update `journal.json`/`snapshot.json`. Throws (writing nothing) if the diff
 * has any validation errors. Warnings are returned, not printed — surfacing
 * them is the caller's job.
 */
export async function generateMigrations(opts: {
    dir: string;
    snapshot: Snapshot;
    dialect: SqlDialect;
    name: string;
}): Promise<GenerateResult> {
    const snapshotPath = resolve(opts.dir, 'snapshot.json');
    const journalPath = resolve(opts.dir, 'journal.json');
    const indexPath = resolve(opts.dir, 'index.ts');

    const prev = await readJsonIfExists<Snapshot>(snapshotPath);
    const journal: Journal = (await readJsonIfExists<Journal>(journalPath)) ?? {
        version: 1,
        dialect: opts.dialect,
        entries: [],
    };

    const next = opts.snapshot;
    const diff = diffSnapshots(prev, next);

    if (diff.errors.length > 0) {
        throw new Error(
            `migration generation failed:\n` +
                diff.errors.map((e) => `  - ${e}`).join('\n')
        );
    }

    if (diff.ops.length === 0) {
        return { status: 'no-changes' };
    }

    const idx =
        journal.entries.length > 0
            ? Math.max(...journal.entries.map((e) => e.idx)) + 1
            : 0;
    const tag = `${String(idx).padStart(4, '0')}_${kebabCase(opts.name)}`;

    await mkdir(opts.dir, { recursive: true });
    await writeFile(
        resolve(opts.dir, `${tag}.ts`),
        renderMigrationFile(diff.ops, opts.dialect),
        'utf-8'
    );

    journal.entries.push({ idx, tag, when: Date.now() });
    await writeFile(journalPath, `${JSON.stringify(journal, null, 2)}\n`, 'utf-8');
    await writeFile(snapshotPath, `${serializeSnapshot(next)}\n`, 'utf-8');
    await writeFile(indexPath, renderIndexFile(journal.entries), 'utf-8');

    return { status: 'generated', file: `${tag}.ts`, tag, warnings: diff.warnings };
}
