/**
 * Migration generator — reads/writes an app's `migrations/` directory
 * (snapshot, journal, generated files), wiring diff → render into one call.
 * Node-only: a dev/CI step, not part of the package's edge-safe main entry.
 */
import type { TableOp } from './diff';
import type { Snapshot, SnapshotTable, SqlDialect } from './model';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { renderTableStatements } from './ddl';
import { diffSnapshots } from './diff';
import { serializeSnapshot } from './model';
import { assertCollapsible, assertReEmittable, parseTableBlocks } from './rebaseline';
import { renderMigrationFile, renderStatementLine } from './render';

/** Outcome of a generate call: nothing changed, or the file/tag/warnings written. */
export type GenerateResult =
    | { status: 'no-changes' }
    | { status: 'generated'; file: string; tag: string; warnings: string[] };

/**
 * What a hand-authored migration sees: the state the chain is at, and the
 * state the descriptors say it should reach. Authors build ops from `next`'s
 * tables, so the SQL that lands matches what the generator would render.
 */
export type MigrationOpsContext = {
    prev: Snapshot | null;
    next: Snapshot;
    dialect: SqlDialect;
};

/** Signature of an ops file passed to {@link generateMigrationFromOps}. */
export type MigrationOpsAuthor = (ctx: MigrationOpsContext) => TableOp[];

type JournalEntry = { idx: number; tag: string; when: number };
type Journal = { version: 1; dialect: SqlDialect; entries: JournalEntry[] };

/** kebab-case a migration name (`"Add Foo"` / `"addFoo"` → `"add-foo"`). */
function kebabCase(name: string): string {
    return name
        .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
        .trim()
        .replace(/[^a-zA-Z0-9]+/g, '-')
        .toLowerCase()
        .replace(/^-+|-+$/g, '');
}

async function readFileIfExists(path: string): Promise<string | null> {
    try {
        return await readFile(path, 'utf-8');
    } catch (err) {
        if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
        throw err;
    }
}

/** A directory's entries, or `[]` when it does not exist. */
async function readDirIfExists(path: string): Promise<string[]> {
    try {
        return await readdir(path);
    } catch (err) {
        if ((err as NodeJS.ErrnoException).code === 'ENOENT') return [];
        throw err;
    }
}

async function readJsonIfExists<T>(path: string): Promise<T | null> {
    const contents = await readFileIfExists(path);
    return contents === null ? null : (JSON.parse(contents) as T);
}

function migrationVarName(idx: number): string {
    return `m${String(idx).padStart(4, '0')}`;
}

/**
 * Regenerate `index.ts` — the static `MigrationProvider` — from every journal
 * entry, ordered by `idx`. Static imports only: an edge bundler can't do
 * runtime `fs` scanning, so sibling specifiers stay extensionless for cross-loader resolution.
 */
function renderIndexFile(entries: JournalEntry[]): string {
    const sorted = [...entries].sort((a, b) => a.idx - b.idx);
    const imports = sorted
        .map((e) => `import * as ${migrationVarName(e.idx)} from './${e.tag}';`)
        .join('\n');
    const providerEntries = sorted
        .map((e) => `            '${e.tag}': ${migrationVarName(e.idx)},`)
        .join('\n');
    return [
        '// generated by astromech db:generate — do not edit; ordering by journal idx',
        "import type { MigrationProvider } from 'kysely/migration';",
        imports,
        '',
        'export const migrationProvider: MigrationProvider = {',
        '    async getMigrations() {',
        '        return {',
        providerEntries,
        '        };',
        '    },',
        '};',
        '',
    ].join('\n');
}

/**
 * Write `index.ts` if what the journal renders to differs from what is on disk.
 * Called on every run, not only when a migration is written, since `index.ts`
 * is derived wholly from `journal.json`.
 */
async function syncIndexFile(dir: string, entries: JournalEntry[]): Promise<void> {
    if (entries.length === 0) return;
    const contents = renderIndexFile(entries);
    const path = resolve(dir, 'index.ts');
    if ((await readFileIfExists(path)) === contents) return;
    await mkdir(dir, { recursive: true });
    await writeFile(path, contents, 'utf-8');
}

/** Read the three files that make up a migrations directory's current state. */
async function readState(
    dir: string,
    dialect: SqlDialect
): Promise<{ prev: Snapshot | null; journal: Journal }> {
    const prev = await readJsonIfExists<Snapshot>(resolve(dir, 'snapshot.json'));
    const journal: Journal = (await readJsonIfExists<Journal>(
        resolve(dir, 'journal.json')
    )) ?? { version: 1, dialect, entries: [] };
    return { prev, journal };
}

/**
 * Render `ops` into a new `NNNN_<name>.ts` and advance the directory's state:
 * append to `journal.json`, rewrite `snapshot.json`, regenerate `index.ts`.
 * The only writer of migration artefacts, for both the diffed and hand-authored paths.
 */
async function writeMigration(opts: {
    dir: string;
    next: Snapshot;
    journal: Journal;
    ops: TableOp[];
    dialect: SqlDialect;
    name: string;
    warnings: string[];
}): Promise<GenerateResult> {
    const { dir, next, journal, ops } = opts;
    const idx =
        journal.entries.length > 0
            ? Math.max(...journal.entries.map((e) => e.idx)) + 1
            : 0;
    const tag = `${String(idx).padStart(4, '0')}_${kebabCase(opts.name)}`;

    // A first migration that only creates tables is the chain's baseline, so it
    // gets the banner per table that `rebaselineMigrations` splits it on.
    const created = ops.flatMap((op) => (op.kind === 'createTable' ? [op.table] : []));
    const source =
        idx === 0 && created.length === ops.length
            ? renderBaselineFile(created.map(renderTableBlock))
            : renderMigrationFile(ops, opts.dialect);

    await mkdir(dir, { recursive: true });
    await writeFile(resolve(dir, `${tag}.ts`), source, 'utf-8');

    journal.entries.push({ idx, tag, when: Date.now() });
    await writeFile(
        resolve(dir, 'journal.json'),
        `${JSON.stringify(journal, null, 2)}\n`,
        'utf-8'
    );
    await writeFile(
        resolve(dir, 'snapshot.json'),
        `${serializeSnapshot(next)}\n`,
        'utf-8'
    );
    await syncIndexFile(dir, journal.entries);

    return { status: 'generated', file: `${tag}.ts`, tag, warnings: opts.warnings };
}

/**
 * Diff the given snapshot against `<dir>/snapshot.json` and, if anything
 * changed, write a new migration. Throws (writing nothing) on validation
 * errors; warnings are returned, not printed.
 */
export async function generateMigrations(opts: {
    dir: string;
    snapshot: Snapshot;
    dialect: SqlDialect;
    name: string;
}): Promise<GenerateResult> {
    const { prev, journal } = await readState(opts.dir, opts.dialect);
    const next = opts.snapshot;
    const diff = diffSnapshots(prev, next);

    if (diff.errors.length > 0) {
        throw new Error(
            `migration generation failed:\n` +
                diff.errors.map((e) => `  - ${e}`).join('\n') +
                `\n\nIf this transition genuinely cannot be diffed, author the ops by hand:\n` +
                `  astromech db:generate --ops <file> --name <name>\n` +
                `See apps/docs/data/migrations.md — "Hand-authored migrations".`
        );
    }

    if (diff.ops.length === 0) {
        await syncIndexFile(opts.dir, journal.entries);
        return { status: 'no-changes' };
    }

    return writeMigration({
        dir: opts.dir,
        next,
        journal,
        ops: diff.ops,
        dialect: opts.dialect,
        name: opts.name,
        warnings: diff.warnings,
    });
}

/**
 * The escape hatch for transitions the differ refuses: the caller supplies
 * the ops directly, and every artefact is still rendered by {@link writeMigration}
 * so `snapshot.json` stays machine-written and in sync with the chain.
 */
export async function generateMigrationFromOps(opts: {
    dir: string;
    snapshot: Snapshot;
    dialect: SqlDialect;
    name: string;
    author: MigrationOpsAuthor;
}): Promise<GenerateResult> {
    const { prev, journal } = await readState(opts.dir, opts.dialect);
    const next = opts.snapshot;

    const ops = opts.author({ prev, next, dialect: opts.dialect });
    if (ops.length === 0) {
        throw new Error(
            'hand-authored migration returned no ops — nothing to write. ' +
                'Return at least one op, or drop the --ops flag and let the differ generate.'
        );
    }

    // Routing around a differ that would have coped is how a chain acquires
    // migrations nobody can regenerate. Not an error (an author may be
    // deliberately replacing a destructive-but-valid plan), but never silent.
    const diff = diffSnapshots(prev, next);
    const warnings: string[] = [];
    if (diff.errors.length === 0 && diff.ops.length === 0) {
        warnings.push(
            'the chain is ALREADY at the descriptor state — this migration changes nothing ' +
                'the schema needs, and `snapshot.json` is unchanged by it. Almost certainly a mistake'
        );
    } else if (diff.errors.length === 0) {
        warnings.push(
            'the differ could generate this transition on its own — a hand-authored ' +
                'migration is not needed here unless you are deliberately replacing its plan'
        );
    }

    return writeMigration({
        dir: opts.dir,
        next,
        journal,
        ops,
        dialect: opts.dialect,
        name: opts.name,
        warnings,
    });
}

export type RebaselineResult = {
    /** The baseline's journal tag, e.g. `0000_baseline`. */
    tag: string;
    /** Tables re-emitted from the snapshot, in file order. */
    emitted: string[];
    /** Tables with no snapshot entry, copied verbatim from the old baseline. */
    preserved: string[];
    /** Files removed, relative to `dir` (collapse only). */
    deleted: string[];
};

/**
 * Rewrite `<dir>/<baseline>.ts` from `snapshot`, keeping the blocks of any table
 * the snapshot does not describe, then rewrite `snapshot.json`, `journal.json`
 * and `index.ts` to match. `collapse` folds a longer chain into the baseline.
 */
export async function rebaselineMigrations(opts: {
    dir: string;
    snapshot: Snapshot;
    dialect: SqlDialect;
    collapse?: boolean;
}): Promise<RebaselineResult> {
    const { dir, snapshot, dialect } = opts;
    const { journal } = await readState(dir, dialect);
    const entries = [...journal.entries].sort((a, b) => a.idx - b.idx);
    const baseline = entries[0];
    if (!baseline) {
        throw new Error(
            `no baseline to rebaseline: "${resolve(dir, 'journal.json')}" has no entries. ` +
                'Run `astromech db:generate` to create the chain first.'
        );
    }

    const later = entries.slice(1);
    if (later.length > 0 && opts.collapse !== true) {
        throw new Error(
            `the chain has ${later.length} ${later.length === 1 ? 'migration' : 'migrations'} past the baseline ` +
                `(${later.map((e) => e.tag).join(', ')}), so re-emitting the baseline alone ` +
                'would leave them replaying on top of it. Pass --collapse to fold the whole ' +
                'chain into a fresh baseline instead.'
        );
    }
    for (const entry of later) {
        const laterPath = resolve(dir, `${entry.tag}.ts`);
        const laterSource = await readFileIfExists(laterPath);
        if (laterSource !== null) assertCollapsible(laterSource, laterPath, snapshot);
    }

    const path = resolve(dir, `${baseline.tag}.ts`);
    const source = await readFileIfExists(path);
    if (source === null) {
        throw new Error(`baseline migration "${path}" does not exist`);
    }

    const blocks = parseTableBlocks(source, path);
    const emitted: string[] = [];
    const preserved: string[] = [];
    const sections: string[] = [];
    for (const block of blocks) {
        const table = snapshot.tables[block.name];
        if (table) {
            assertReEmittable(block, path);
            sections.push(renderTableBlock(table));
            emitted.push(block.name);
        } else {
            sections.push(block.source);
            preserved.push(block.name);
        }
    }
    for (const [name, table] of Object.entries(snapshot.tables)) {
        if (emitted.includes(name)) continue;
        sections.push(renderTableBlock(table));
        emitted.push(name);
    }

    await writeFile(
        path,
        renderBaselineFile(sections, renderRebaselineComment()),
        'utf-8'
    );

    const deleted: string[] = [];
    if (later.length > 0) {
        for (const entry of later) {
            await rm(resolve(dir, `${entry.tag}.ts`), { force: true });
            deleted.push(`${entry.tag}.ts`);
        }
        const ops = await readDirIfExists(resolve(dir, 'ops'));
        if (ops.length > 0) {
            await rm(resolve(dir, 'ops'), { recursive: true, force: true });
            deleted.push(...ops.map((file) => `ops/${file}`));
        }
    }

    const collapsed: Journal = {
        version: 1,
        dialect,
        entries: [{ idx: 0, tag: baseline.tag, when: baseline.when }],
    };
    await writeFile(
        resolve(dir, 'journal.json'),
        `${JSON.stringify(collapsed, null, 2)}\n`,
        'utf-8'
    );
    await writeFile(
        resolve(dir, 'snapshot.json'),
        `${serializeSnapshot(snapshot)}\n`,
        'utf-8'
    );
    await syncIndexFile(dir, collapsed.entries);

    return { tag: baseline.tag, emitted, preserved, deleted };
}

/** One table's section: its banner, then a `sql` statement per DDL statement. */
function renderTableBlock(table: SnapshotTable): string {
    const banner = `    // ── ${table.name} `.padEnd(78, '─');
    return [banner, ...renderTableStatements(table).map(renderStatementLine)].join('\n');
}

/** The doc comment over a baseline `rebaselineMigrations` rewrote. */
function renderRebaselineComment(): string[] {
    const today = new Date().toISOString().slice(0, 10);
    return [
        '/**',
        ' * Baseline migration — the whole schema as one forward migration.',
        ' *',
        ` * Regenerated by \`astromech db:rebaseline\` on ${today}: a table the`,
        ' * descriptors describe is emitter output, a table they do not is copied verbatim',
        ' * from the previous baseline. Rewriting history is legal only before a release.',
        ' */',
        '',
    ];
}

/** A baseline module: `up()` holding one table section per entry, under `comment`'s lines. */
function renderBaselineFile(sections: string[], comment: string[] = []): string {
    return [
        ...comment,
        "import { sql, type Kysely } from 'kysely';",
        '',
        'export async function up(db: Kysely<unknown>): Promise<void> {',
        sections.join('\n\n'),
        '}',
        '',
    ].join('\n');
}
