/**
 * Migration generator — reads/writes an app's `migrations/` directory
 * (`snapshot.json`, `journal.json`, the generated `.ts` migration files, and
 * `index.ts`), wiring `diff.ts` (snapshot diff) → `render.ts` (diff → SQL/TS)
 * into one call.
 *
 * Node-only (uses `node:fs/promises` + `node:path`) — generation is a dev/CI
 * step, never a runtime one. It is deliberately NOT part of the package's main
 * entry: `.` stays pure and edge-safe, this module is the `./generate` subpath.
 *
 * Journal ordering is by `idx` alone and there is no `id`/`prevId` snapshot
 * chain, so a divergent parallel generation run surfaces as a `snapshot.json`
 * merge conflict rather than a silent hash mismatch.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { diffSnapshots, type TableOp } from './diff.js';
import { renderMigrationFile } from './render.js';
import { serializeSnapshot, type Snapshot, type SqlDialect } from './model.js';

export type GenerateResult =
    | { status: 'no-changes' }
    | { status: 'generated'; file: string; tag: string; warnings: string[] };

/**
 * What a hand-authored migration sees: the state the chain is currently at, and
 * the state the descriptors say it should reach. Authors build ops out of
 * `next`'s tables rather than re-deriving them, so the SQL that lands is the
 * same SQL the generator would have rendered.
 */
export type MigrationOpsContext = {
    prev: Snapshot | null;
    next: Snapshot;
    dialect: SqlDialect;
};

/** Signature of an ops file passed to {@link generateMigrationFromOps}. */
export type MigrationOpsAuthor = (ctx: MigrationOpsContext) => TableOp[];

type JournalEntry = { idx: number; tag: string; when: number };
type Journal = { version: 1; dialect: SqlDialect; entries: JournalEntry[] };

/** kebab-case a migration name (`"Add Foo"` / `"addFoo"` → `"add-foo"`). */
function kebabCase(name: string): string {
    return name
        .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
        .trim()
        .replace(/[^a-zA-Z0-9]+/g, '-')
        .toLowerCase()
        .replace(/^-+|-+$/g, '');
}

async function readJsonIfExists<T>(path: string): Promise<T | null> {
    try {
        return JSON.parse(await readFile(path, 'utf-8')) as T;
    } catch (err) {
        if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
        throw err;
    }
}

function migrationVarName(idx: number): string {
    return `m${String(idx).padStart(4, '0')}`;
}

/** Regenerate `index.ts` — the static `MigrationProvider` — from every
 *  journal entry, ordered by `idx`. Static imports only (no dynamic
 *  discovery): an edge bundler can't do runtime `fs` scanning. */
function renderIndexFile(entries: JournalEntry[]): string {
    const sorted = [...entries].sort((a, b) => a.idx - b.idx);
    const imports = sorted
        .map((e) => `import * as ${migrationVarName(e.idx)} from './${e.tag}.js';`)
        .join('\n');
    const providerEntries = sorted
        .map((e) => `            '${e.tag}': ${migrationVarName(e.idx)},`)
        .join('\n');
    return [
        '// generated by astromech db:generate — do not edit; ordering by journal idx',
        "import type { MigrationProvider } from 'kysely';",
        imports,
        '',
        'export const migrationProvider: MigrationProvider = {',
        '    async getMigrations() {',
        '        return {',
        providerEntries,
        '        };',
        '    },',
        '};',
        '',
    ].join('\n');
}

/** Read the three files that make up a migrations directory's current state. */
async function readState(
    dir: string,
    dialect: SqlDialect
): Promise<{ prev: Snapshot | null; journal: Journal }> {
    const prev = await readJsonIfExists<Snapshot>(resolve(dir, 'snapshot.json'));
    const journal: Journal = (await readJsonIfExists<Journal>(
        resolve(dir, 'journal.json')
    )) ?? { version: 1, dialect, entries: [] };
    return { prev, journal };
}

/**
 * Render `ops` into a new `NNNN_<name>.ts` and advance the directory's state:
 * append to `journal.json`, rewrite `snapshot.json` to `next`, regenerate
 * `index.ts`.
 *
 * The ONLY writer of migration artefacts. Both the diffed path and the
 * hand-authored path go through it, which is what keeps `snapshot.json` a
 * machine-written file in every case — a hand-edited snapshot would turn the
 * drift gate into a lie, since the gate's whole job is to compare that file
 * against the descriptors.
 */
async function writeMigration(opts: {
    dir: string;
    next: Snapshot;
    journal: Journal;
    ops: TableOp[];
    dialect: SqlDialect;
    name: string;
    warnings: string[];
}): Promise<GenerateResult> {
    const { dir, next, journal, ops } = opts;
    const idx =
        journal.entries.length > 0
            ? Math.max(...journal.entries.map((e) => e.idx)) + 1
            : 0;
    const tag = `${String(idx).padStart(4, '0')}_${kebabCase(opts.name)}`;

    await mkdir(dir, { recursive: true });
    await writeFile(
        resolve(dir, `${tag}.ts`),
        renderMigrationFile(ops, opts.dialect),
        'utf-8'
    );

    journal.entries.push({ idx, tag, when: Date.now() });
    await writeFile(
        resolve(dir, 'journal.json'),
        `${JSON.stringify(journal, null, 2)}\n`,
        'utf-8'
    );
    await writeFile(
        resolve(dir, 'snapshot.json'),
        `${serializeSnapshot(next)}\n`,
        'utf-8'
    );
    await writeFile(resolve(dir, 'index.ts'), renderIndexFile(journal.entries), 'utf-8');

    return { status: 'generated', file: `${tag}.ts`, tag, warnings: opts.warnings };
}

/**
 * Diff the given snapshot against `<dir>/snapshot.json` and, if anything
 * changed, write a new migration. Throws (writing nothing) if the diff has any
 * validation errors. Warnings are returned, not printed — surfacing them is the
 * caller's job.
 */
export async function generateMigrations(opts: {
    dir: string;
    snapshot: Snapshot;
    dialect: SqlDialect;
    name: string;
}): Promise<GenerateResult> {
    const { prev, journal } = await readState(opts.dir, opts.dialect);
    const next = opts.snapshot;
    const diff = diffSnapshots(prev, next);

    if (diff.errors.length > 0) {
        throw new Error(
            `migration generation failed:\n` +
                diff.errors.map((e) => `  - ${e}`).join('\n') +
                `\n\nIf this transition genuinely cannot be diffed, author the ops by hand:\n` +
                `  astromech db:generate --ops <file> --name <name>\n` +
                `See apps/docs/data/migrations.md — "Hand-authored migrations".`
        );
    }

    if (diff.ops.length === 0) {
        return { status: 'no-changes' };
    }

    return writeMigration({
        dir: opts.dir,
        next,
        journal,
        ops: diff.ops,
        dialect: opts.dialect,
        name: opts.name,
        warnings: diff.warnings,
    });
}

/**
 * The escape hatch for transitions the differ refuses.
 *
 * The generator has no rename op and its rebuild path copies same-named columns
 * only, so a few genuine reshapes (swapping a primary key, adding a NOT NULL
 * column with no SQL-literal default) have no derivable plan. Rather than
 * hand-writing a migration and its artefacts — which is how `snapshot.json`
 * ends up disagreeing with the chain — the author supplies only the OPS, and
 * every artefact is still rendered by {@link writeMigration}.
 *
 * The division of labour: the generator owns the destination, the author owns
 * the route. `snapshot.json` is still written from the descriptors, so a
 * following `db:generate` must report no changes, and the migration-chain ↔
 * descriptor parity test still executes the real SQL and compares the result.
 * Those two together are what verify a hand-authored route actually arrives.
 */
export async function generateMigrationFromOps(opts: {
    dir: string;
    snapshot: Snapshot;
    dialect: SqlDialect;
    name: string;
    author: MigrationOpsAuthor;
}): Promise<GenerateResult> {
    const { prev, journal } = await readState(opts.dir, opts.dialect);
    const next = opts.snapshot;

    const ops = opts.author({ prev, next, dialect: opts.dialect });
    if (ops.length === 0) {
        throw new Error(
            'hand-authored migration returned no ops — nothing to write. ' +
                'Return at least one op, or drop the --ops flag and let the differ generate.'
        );
    }

    // Routing around a differ that would have coped is how a chain acquires
    // migrations nobody can regenerate. Not an error (an author may be
    // deliberately replacing a destructive-but-valid plan), but never silent.
    const diff = diffSnapshots(prev, next);
    const warnings: string[] = [];
    if (diff.errors.length === 0 && diff.ops.length === 0) {
        warnings.push(
            'the chain is ALREADY at the descriptor state — this migration changes nothing ' +
                'the schema needs, and `snapshot.json` is unchanged by it. Almost certainly a mistake'
        );
    } else if (diff.errors.length === 0) {
        warnings.push(
            'the differ could generate this transition on its own — a hand-authored ' +
                'migration is not needed here unless you are deliberately replacing its plan'
        );
    }

    return writeMigration({
        dir: opts.dir,
        next,
        journal,
        ops,
        dialect: opts.dialect,
        name: opts.name,
        warnings,
    });
}
