/**
 * `astromech db:generate`
 *
 * Diffs the core descriptors (`CORE_TABLES`) against the app's
 * `migrations/snapshot.json` and writes a new migration if anything changed
 * (see `database/generate.ts`). Plugin-owned tables are generated by the plugin
 * itself via `astromech plugin:generate`, into the plugin package's own
 * `migrations/` directory — this covers `CORE_TABLES` only.
 */

import { defineCommand } from 'citty';
import { resolve } from 'node:path';
import { loadConfig } from '../config.js';
import { generateMigrations } from '@/database/generate.js';
import { CORE_TABLES } from '@/database/schema.js';

export default defineCommand({
    meta: {
        name: 'db:generate',
        description: 'Generate migrations for this app (core + plugin schemas)',
    },
    args: {
        config: { type: 'string', description: 'Path to astromech.config.ts' },
        name: { type: 'string', description: 'migration name (kebab-case)' },
    },
    async run({ args }) {
        await loadConfig(args.config);
        const result = await generateMigrations({
            dir: resolve(process.cwd(), 'migrations'),
            tables: CORE_TABLES,
            dialect: 'sqlite',
            name: args.name ?? 'migration',
        });
        if (result.status === 'no-changes') {
            console.log('[astromech db:generate] no changes');
        } else {
            console.log(`[astromech db:generate] generated migrations/${result.file}`);
        }
    },
});
